// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avmlofmzvqqzjeozbkig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2bWxvZm16dnFxemplb3pia2lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1Njk1OTQsImV4cCI6MjA3MjE0NTU5NH0.0zquqjXg2hUqXkFkXfj13aVRbE3ZVYmA6Mk90P4yX2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});